# **Brazil**

## Brazil states

In [ ]:
from scraping import get_brazil_states

display(get_brazil_states())

,Flag and name,Code,Capital,Largest city,Area(km2)[20],Population(2022)[21],"Density (perkm2, 2022)","GDP (R$millions, 2022)[22]",HDI(2022)[23]
0,Acre,AC,Rio Branco,Rio Branco,164123,892000,6.34,21000,0.719
1,Alagoas,AL,Maceió,Maceió,27779,3345000,125.52,73000,0.683
2,Amapá,AP,Macapá,Macapá,142829,845000,2.63,9000,0.740
3,Amazonas,AM,Manaus,Manaus,1559159,4156000,2.58,103000,0.733
4,Bahia,BA,Salvador,Salvador,564733,14942000,30.52,257000,0.714
5,Ceará,CE,Fortaleza,Fortaleza,148921,8870000,60.33,157000,0.735
6,Distrito Federal,DF,Brasília,Brasília,5780,3135000,493.00,249000,0.850
7,Espírito Santo,ES,Vitória,Serra,46095,3982000,80.63,125000,0.772
8,Goiás,GO,Goiânia,Goiânia,340112,7116000,18.46,202000,0.769
9,Maranhão,MA,São Luís,São Luís,331937,7134000,19.03,102000,0.687
10,Mato Grosso,MT,Cuiabá,Cuiabá,903366,3537000,4.01,142000,0.774
11,Mato Grosso do Sul,MS,Campo Grande,Campo Grande,357146,2816000,7.83,107000,0.766
12,Minas Gerais,MG,Belo Horizonte,Belo Horizonte,586522,21212000,31.72,583000,0.787
13,Pará,PA,Belém,Belém,1247955,8623000,7.02,156000,0.698
14,Paraíba,PB,João Pessoa,João Pessoa,56470,4103000,78.93,60000,0.722
15,Paraná,PR,Curitiba,Curitiba,199308,11515000,43.46,417000,0.792
16,Pernambuco,PE,Recife,Recife,98148,9599000,103.83,201000,0.727
17,Piauí,PI,Teresina,Teresina,251578,3292000,9.73,26000,0.697
18,Rio de Janeiro,RJ,Rio de Janeiro,Rio de Janeiro,43780,17309000,387.46,693000,0.796
19,Rio Grande do Norte,RN,Natal,Natal,52811,3552000,62.74,76000,0.731
20,Rio Grande do Sul,RS,Porto Alegre,Porto Alegre,281730,11407000,36.84,444000,0.787
21,Rondônia,RO,Porto Velho,Porto Velho,237591,1803000,7.34,19000,0.725
22,Roraima,RR,Boa Vista,Boa Vista,224301,651000,2.54,8000,0.752
23,Santa Catarina,SC,Florianópolis,Joinville,95736,7175000,69.74,293000,0.808
24,São Paulo,SP,São Paulo,São Paulo,248223,46004000,175.73,1964000,0.826
25,Sergipe,SE,Aracaju,Aracaju,21915,2317000,97.64,38000,0.702
26,Tocantins,TO,Palmas,Palmas,277721,1605000,5.74,21000,0.743

## Brazil municipalities

In [ ]:
from scraping import scrap_brazil_municipalities

display(scrap_brazil_municipalities())

ValueError: No objects to concatenate