In [ ]:
print('Hellooo')

Hellooo

In [ ]:
revenus = [1800, 1500, 2200, 3000, 2172]

In [ ]:
def moyenne(liste):
    return sum(liste)/len(liste)
moyenne(revenus) # => 2135.0

2134.4

In [ ]:
import numpy as np
np.mean(revenus)

2134.4

In [ ]:
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]

In [ ]:
a_rev = np.array(revenus)
a_rev

array([1800, 1500, 2200, 3000, 2172])

In [ ]:
a_rev.dtype

dtype('int32')

In [ ]:
a_rev[1] = 1
a_rev

array([1800,    1, 2200, 3000, 2172])

In [ ]:
a_rev[1:5:2]

array([   1, 3000])

In [ ]:
a_rev[::-1]

array([2172, 3000, 2200,    1, 1800])

In [ ]:
a_rev[a_rev > 2000]

array([2200, 3000, 2172])

In [ ]:
a_rev > 2000

array([False, False,  True,  True,  True])

In [ ]:
a_rev[(a_rev > 2000) & (a_rev < 2500)]

array([2200, 2172])

In [ ]:
a_rev[(a_rev > 2000) & (a_rev < 2500)] = a_rev[(a_rev > 2000) & (a_rev < 2500)] / 2

In [ ]:
a_rev

array([1800,    1, 1100, 3000, 1086])

In [ ]:
len(a_rev)
a_rev.shape

(5,)

In [ ]:
a_rev.mean()

1397.4

In [ ]:
np.ma.median(a_rev)

1100.0

In [ ]:
a_rev.argmin()

1

In [ ]:
a_rev.sort()
a_rev

array([   1, 1086, 1100, 1800, 3000])

In [ ]:
a_rev.sum()

6987

In [ ]:
tab1 = np.array([[1, 2],
    [3, 4],
    [5, 6]])

tab2 = np.array([[1, 2, 3],
        [4, 5, 6]])
print(tab1)
tab2

[[1 2]
 [3 4]
 [5 6]]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.random.randint(0, 2, size = (2, 3, 5))

array([[[1, 0, 1, 1, 1],
        [1, 0, 0, 1, 0],
        [0, 1, 0, 0, 0]],

       [[0, 0, 1, 0, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 0, 0, 1]]])

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 10], [15, 20]])
C = np.array([[2, 4, 6], [8, 10, 12]])

A+B
AC = A @ B
AC

array([[ 35,  50],
       [ 75, 110]])

In [ ]:
a = np.linspace(5, 10, 11)
print(a)
a[-3:]

[ 5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.   9.5 10. ]

array([ 9. ,  9.5, 10. ])

In [ ]:
import pandas as pd
df = pd.read_csv('~/Downloads/P2C1_clients/clients.csv')
#display(df.head())
#display(df.tail())
display(df)
df.shape
df.dtypes
display(df.values)

     identifiant                            email                nom genre
0              0        LaurentDagenais@rhyta.com   Laurent Dagenais     M
1              1            GuyMarois@fleckens.hu         Guy Marois     M
2              2        BeaufortLesage@einrot.com    Beaufort Lesage     M
3              3        RussellDurand@armyspy.com     Russell Durand     M
4              4             AlexisRiel@rhyta.com        Alexis Riel     M
..           ...                              ...                ...   ...
223          223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224          224    ApollineMichaud@superrito.com   Apolline Michaud     F
225          225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226          226     FleurCaouette@jourrapide.com     Fleur Caouette     F
227          227      FrancisMasse@jourrapide.com      Francis Masse     M

[228 rows x 4 columns]

array([[0, 'LaurentDagenais@rhyta.com', 'Laurent Dagenais', 'M'],
       [1, 'GuyMarois@fleckens.hu', 'Guy Marois', 'M'],
       [2, 'BeaufortLesage@einrot.com', 'Beaufort Lesage', 'M'],
       [3, 'RussellDurand@armyspy.com', 'Russell Durand', 'M'],
       [4, 'AlexisRiel@rhyta.com', 'Alexis Riel', 'M'],
       [5, 'LeonLapresse@cuvox.de', 'Leon Lapresse', 'M'],
       [6, 'OrvilleRouthier@gustr.com', 'Orville Routhier', 'M'],
       [7, 'AgramantPepin@dayrep.com', 'Agramant Pepin', 'M'],
       [8, 'AiglentinaLambert@fleckens.hu', 'Aiglentina Lambert', 'F'],
       [9, 'TheodoreClavet@teleworm.us', 'Theodore Clavet', 'M'],
       [10, 'ByronLefebvre@jourrapide.com', 'Byron Lefebvre', 'M'],
       [11, 'FlorusDevoe@einrot.com', 'Florus Devoe', 'M'],
       [12, 'NormandArsenault@armyspy.com', 'Normand Arsenault', 'M'],
       [13, 'AcelineHughes@jourrapide.com', 'Aceline Hughes', 'F'],
       [14, 'GastonBrisette@superrito.com', 'Gaston Brisette', 'M'],
       [15, 'AgateGrandbois@gustr.com', 'Agate Grandbois', 'F'],
       [16, 'AgricanFoucault@jourrapide.com', 'Agrican Foucault', 'M'],
       [17, 'PrunellaJosseaume@armyspy.com', 'Prunella Josseaume', 'F'],
       [18, 'YseultCharest@armyspy.com', 'Yseult Charest', 'F'],
       [19, 'DorotheeAupry@cuvox.de', 'Dorothee Aupry', 'F'],
       [20, 'AmauryReault@teleworm.us', 'Amaury Reault', 'M'],
       [21, 'GillesBeauchamps@superrito.com', 'Gilles Beauchamps', 'M'],
       [22, 'FranckDumont@gustr.com', 'Franck Dumont', 'M'],
       [23, 'DelmareLHeureux@dayrep.com', 'Delmare L Heureux', 'F'],
       [24, 'AlphonseCantin@cuvox.de', 'Alphonse Cantin', 'M'],
       [25, 'BlondelleRochon@gustr.com', 'Blondelle Rochon', 'F'],
       [26, 'SavilleBernard@armyspy.com', 'Saville Bernard', 'M'],
       [27, 'AnnetteJolicoeur@armyspy.com', 'Annette Jolicoeur', 'F'],
       [28, 'BradamateMichel@armyspy.com', 'Bradamate Michel', 'F'],
       [29, 'HilaireFrappier@armyspy.com', 'Hilaire Frappier', 'F'],
       [30, 'MarieBriard@gustr.com', 'Marie Briard', 'F'],
       [31, 'MadeleineBatard@superrito.com', 'Madeleine Batard', 'F'],
       [32, 'ArberGarcia@dayrep.com', 'Arber Garcia', 'M'],
       [33, 'SaberViens@superrito.com', 'Saber Viens', 'M'],
       [34, 'ArnaudDubois@rhyta.com', 'Arnaud Dubois', 'M'],
       [35, 'PryorBeauchamp@dayrep.com', 'Pryor Beauchamp', 'M'],
       [36, 'AlphonsePotvin@armyspy.com', 'Alphonse Potvin', 'M'],
       [37, 'FitzLafontaine@dayrep.com', 'Fitz Lafontaine', 'M'],
       [38, 'DelmareLamothe@gustr.com', 'Delmare Lamothe', 'F'],
       [39, 'DaisiBoileau@jourrapide.com', 'Daisi Boileau', 'F'],
       [40, 'SomerPaquette@jourrapide.com', 'Somer Paquette', 'M'],
       [41, 'OlivieCourtemanche@armyspy.com', 'Olivie Courtemanche', 'F'],
       [42, 'GermainHughes@teleworm.us', 'Germain Hughes', 'M'],
       [43, 'MorganaBellemare@superrito.com', 'Morgana Bellemare', 'F'],
       [44, 'MerciMorin@gustr.com', 'Merci Morin', 'F'],
       [45, 'VerneyBedard@dayrep.com', 'Verney Bedard', 'M'],
       [46, 'IgnaceAudibert@armyspy.com', 'Ignace Audibert', 'M'],
       [47, 'FranckBinet@superrito.com', 'Franck Binet', 'M'],
       [48, 'SumnerRocheleau@einrot.com', 'Sumner Rocheleau', 'M'],
       [49, 'AubertPatel@armyspy.com', 'Aubert Patel', 'M'],
       [50, 'SumnerLaprise@superrito.com', 'Sumner Laprise', 'M'],
       [51, 'MadeleineLeveille@dayrep.com', 'Madeleine Leveille', 'F'],
       [52, 'BelisardaGuedry@dayrep.com', 'Belisarda Guedry', 'F'],
       [53, 'ZurieTheberge@gustr.com', 'Zurie Theberge', 'F'],
       [54, 'ErmengardiBousquet@dayrep.com', 'Ermengardi Bousquet', 'F'],
       [55, 'FlorenceBeaudoin@einrot.com', 'Florence Beaudoin', 'F'],
       [56, 'LeoneCrete@armyspy.com', 'Leone Crete', 'F'],
       [57, 'SearlaitCote@superrito.com', 'Searlait Cote', 'F'],
       [58, 'AlphonsineBourassa@cuvox.de', 'Alphonsine Bourassa', 'F'],
       [59, 'DidianeDAubigne@einrot.com', 'Didiane D Aubigne', 'F'],
       [60, 'EdouardLacroix@cuvox.de', 'Edouard Lacroix', 'M'],
       [61, 'OdeletteCharron@superrito.com', 'Odelette Charron', 'F'],
       [62, 'AleronBerard@rhyta.com', 'Aleron Berard', 'M'],
       [63, 'SylvieDuranseau@einrot.com', 'Sylvie Duranseau', 'F'],
       [64, 'YvetteDAvis@cuvox.de', 'Yvette D Avis', 'F'],
       [65, 'SolaineLecuyer@dayrep.com', 'Solaine Lecuyer', 'F'],
       [66, 'CourtlandDavid@cuvox.de', 'Courtland David', 'M'],
       [67, 'PatienceCharbonneau@jourrapide.com', 'Patience Charbonneau',
        'F'],
       [68, 'EmmanuelLanctot@cuvox.de', 'Emmanuel Lanctot', 'M'],
       [69, 'MusetteProvencher@armyspy.com', 'Musette Provencher', 'F'],
       [70, 'MorganaMarchesseault@teleworm.us', 'Morgana Marchesseault',
        'F'],
       [71, 'ViolletteArnoux@cuvox.de', 'Viollette Arnoux', 'F'],
       [72, 'SlainieGregoire@cuvox.de', 'Slainie Gregoire', 'F'],
       [73, 'GarlandLagueux@rhyta.com', 'Garland Lagueux', 'F'],
       [74, 'FerragusGrimard@cuvox.de', 'Ferragus Grimard', 'M'],
       [75, 'JeanTollmache@einrot.com', 'Jean Tollmache', 'M'],
       [76, 'LanceParent@teleworm.us', 'Lance Parent', 'M'],
       [77, 'CheneyChaloux@cuvox.de', 'Cheney Chaloux', 'M'],
       [78, 'PierpontLamarre@superrito.com', 'Pierpont Lamarre', 'M'],
       [79, 'ComforteQuerry@superrito.com', 'Comforte Querry', 'F'],
       [80, 'NadineMasson@teleworm.us', 'Nadine Masson', 'F'],
       [81, 'FranceLaderoute@jourrapide.com', 'France Laderoute', 'F'],
       [82, 'LothairBonenfant@dayrep.com', 'Lothair Bonenfant', 'M'],
       [83, 'OlivieNorbert@cuvox.de', 'Olivie Norbert', 'F'],
       [84, 'SomerMarleau@cuvox.de', 'Somer Marleau', 'M'],
       [85, 'AstridJolicoeur@superrito.com', 'Astrid Jolicoeur', 'F'],
       [86, 'OlivierGaillard@superrito.com', 'Olivier Gaillard', 'M'],
       [87, 'PhilipPinneau@teleworm.us', 'Philip Pinneau', 'M'],
       [88, 'AlexisLagrange@gustr.com', 'Alexis Lagrange', 'M'],
       [89, 'HeloiseGregoire@dayrep.com', 'Heloise Gregoire', 'F'],
       [90, 'DexterDavid@fleckens.hu', 'Dexter David', 'M'],
       [91, 'JacquesMethot@cuvox.de', 'Jacques Methot', 'M'],
       [92, 'AnceloteDesforges@cuvox.de', 'Ancelote Desforges', 'F'],
       [93, 'JulietteOuellet@rhyta.com', 'Juliette Ouellet', 'F'],
       [94, 'AvrilSylvain@superrito.com', 'Avril Sylvain', 'F'],
       [95, 'RachellePlaisance@armyspy.com', 'Rachelle Plaisance', 'F'],
       [96, 'BenjaminLabrie@fleckens.hu', 'Benjamin Labrie', 'M'],
       [97, 'LaureBondy@superrito.com', 'Laure Bondy', 'F'],
       [98, 'NatalieLeveille@rhyta.com', 'Natalie Leveille', 'F'],
       [99, 'SydneyGuibord@superrito.com', 'Sydney Guibord', 'F'],
       [100, 'ZdenekVadnais@superrito.com', 'Zdenek Vadnais', 'M'],
       [101, 'LoyalQuenneville@superrito.com', 'Loyal Quenneville', 'M'],
       [102, 'ErnestTachel@cuvox.de', 'Ernest Tachel', 'M'],
       [103, 'MatthieuPouchard@teleworm.us', 'Matthieu Pouchard', 'M'],
       [104, 'SearlasArtois@rhyta.com', 'Searlas Artois', 'M'],
       [105, 'ArnoLeBatelier@einrot.com', 'Arno Le Batelier', 'M'],
       [106, 'EstellePoisson@jourrapide.com', 'Estelle Poisson', 'F'],
       [107, 'HarcourtCharpentier@cuvox.de', 'Harcourt Charpentier', 'M'],
       [108, 'CrescentLavallee@armyspy.com', 'Crescent Lavallee', 'F'],
       [109, 'EugeniaVadeboncoeur@cuvox.de', 'Eugenia Vadeboncoeur', 'F'],
       [110, 'GenevreLabrie@cuvox.de', 'Genevre Labrie', 'F'],
       [111, 'NormandCote@dayrep.com', 'Normand Cote', 'M'],
       [112, 'ZoeLeclair@gustr.com', 'Zoe Leclair', 'F'],
       [113, 'PhillipaPerrault@einrot.com', 'Phillipa Perrault', 'F'],
       [114, 'EliseDesrosiers@jourrapide.com', 'Elise Desrosiers', 'F'],
       [115, 'RussellRochon@superrito.com', 'Russell Rochon', 'M'],
       [116, 'BeldaLauzier@armyspy.com', 'Belda Lauzier', 'F'],
       [117, 'AlphonsineSacre@einrot.com', 'Alphonsine Sacre', 'F'],
       [118, 'AubineLabelle@cuvox.de', 'Aubine Labelle', 'F'],
       [119, 'EmileVadnais@rhyta.com', 'Emile Vadnais', 'M'],
       [120, 'ArienneCantin@superrito.com', 'Arienne Cantin', 'F'],
       [121, 'JacquesMarcheterre@einrot.com', 'Jacques Marcheterre', 'M'],
       [122, 'EliotDupuis@gustr.com', 'Eliot Dupuis', 'M'],
       [123, 'ArthurPlante@jourrapide.com', 'Arthur Plante', 'M'],
       [124, 'SacripantLabrie@armyspy.com', 'Sacripant Labrie', 'M'],
       [125, 'SibylaLizotte@cuvox.de', 'Sibyla Lizotte', 'F'],
       [126, 'ChristianLaberge@armyspy.com', 'Christian Laberge', 'M'],
       [127, 'VickDavid@gustr.com', 'Vick David', 'M'],
       [128, 'ComforteCloutier@einrot.com', 'Comforte Cloutier', 'F'],
       [129, 'ClaudeGalarneau@armyspy.com', 'Claude Galarneau', 'M'],
       [130, 'ElisePerrault@superrito.com', 'Elise Perrault', 'F'],
       [131, 'LoringRocheleau@cuvox.de', 'Loring Rocheleau', 'M'],
       [132, 'MathildeSansouci@superrito.com', 'Mathilde Sansouci', 'F'],
       [133, 'AmaurySirois@superrito.com', 'Amaury Sirois', 'M'],
       [134, 'ChristelleLandry@jourrapide.com', 'Christelle Landry', 'F'],
       [135, 'AdelaideBrousse@gustr.com', 'Adelaide Brousse', 'F'],
       [136, 'BriceFaure@einrot.com', 'Brice Faure', 'M'],
       [137, 'AlaineHervieux@rhyta.com', 'Alaine Hervieux', 'F'],
       [138, 'LanceCroteau@einrot.com', 'Lance Croteau', 'M'],
       [139, 'AurelieBazinet@dayrep.com', 'Aurelie Bazinet', 'F'],
       [140, 'AstolphoVeronneau@teleworm.us', 'Astolpho Veronneau', 'M'],
       [141, 'JolieDeblois@armyspy.com', 'Jolie Deblois', 'F'],
       [142, 'MireilleParenteau@superrito.com', 'Mireille Parenteau',
        'F'],
       [143, 'ToussaintBrodeur@rhyta.com', 'Toussaint Brodeur', 'M'],
       [144, 'PorterSimard@armyspy.com', 'Porter Simard', 'M'],
       [145, 'JeromedeLaunay@fleckens.hu', 'Jeromede Launay', 'M'],
       [146, 'LowellPatel@rhyta.com', 'Lowell Patel', 'M'],
       [147, 'GarlandMarcheterre@fleckens.hu', 'Garland Marcheterre',
        'F'],
       [148, 'OlivierAube@armyspy.com', 'Olivier Aube', 'M'],
       [149, 'FrontinoBrian@einrot.com', 'Frontino Brian', 'M'],
       [150, 'RochMireault@gustr.com', 'Roch Mireault', 'M'],
       [151, 'NathalieCormier@cuvox.de', 'Nathalie Cormier', 'F'],
       [152, 'VallisMainville@gustr.com', 'Vallis Mainville', 'M'],
       [153, 'DanielleNeufville@teleworm.us', 'Danielle Neufville', 'F'],
       [154, 'AllyrianeRacine@gustr.com', 'Allyriane Racine', 'F'],
       [155, 'PierpontFlamand@fleckens.hu', 'Pierpont Flamand', 'M'],
       [156, 'DanielHuot@rhyta.com', 'Daniel Huot', 'M'],
       [157, 'HughPoisson@fleckens.hu', 'Hugh Poisson', 'M'],
       [158, 'YoletteMoreau@dayrep.com', 'Yolette Moreau', 'F'],
       [159, 'GasparReault@dayrep.com', 'Gaspar Reault', 'M'],
       [160, 'DelitBisaillon@teleworm.us', 'Delit Bisaillon', 'F'],
       [161, 'ManonDastous@armyspy.com', 'Manon Dastous', 'F'],
       [162, 'LoyalFouquet@armyspy.com', 'Loyal Fouquet', 'M'],
       [163, 'ApollineLaframboise@teleworm.us', 'Apolline Laframboise',
        'F'],
       [164, 'OrielMiron@jourrapide.com', 'Oriel Miron', 'F'],
       [165, 'LianeLaGarde@cuvox.de', 'Liane La Garde', 'F'],
       [166, 'AnastasieCroteau@rhyta.com', 'Anastasie Croteau', 'F'],
       [167, 'VerneyCourse@armyspy.com', 'Verney Course', 'M'],
       [168, 'VoletaAdler@armyspy.com', 'Voleta Adler', 'F'],
       [169, 'PlattParent@jourrapide.com', 'Platt Parent', 'M'],
       [170, 'BlondelleAilleboust@gustr.com', 'Blondelle Ailleboust',
        'F'],
       [171, 'AurelieDesnoyer@armyspy.com', 'Aurelie Desnoyer', 'F'],
       [172, 'AvelaineGadbois@dayrep.com', 'Avelaine Gadbois', 'F'],
       [173, 'BriceGrondin@fleckens.hu', 'Brice Grondin', 'M'],
       [174, 'ZacharieDuplessis@rhyta.com', 'Zacharie Duplessis', 'M'],
       [175, 'OgierGervais@gustr.com', 'Ogier Gervais', 'M'],
       [176, 'FusbertaRancourt@rhyta.com', 'Fusberta Rancourt', 'F'],
       [177, 'CamilleLaurent@superrito.com', 'Camille Laurent', 'F'],
       [178, 'CeriseMontminy@dayrep.com', 'Cerise Montminy', 'F'],
       [179, 'JosetteRiquier@armyspy.com', 'Josette Riquier', 'F'],
       [180, 'AgnesBriard@cuvox.de', 'Agnes Briard', 'F'],
       [181, 'AvrilRocheleau@fleckens.hu', 'Avril Rocheleau', 'F'],
       [182, 'BenoitGauvin@teleworm.us', 'Benoit Gauvin', 'M'],
       [183, 'HeloiseMarcil@fleckens.hu', 'Heloise Marcil', 'F'],
       [184, 'RolandDupont@einrot.com', 'Roland Dupont', 'M'],
       [185, 'SolaineLabrecque@fleckens.hu', 'Solaine Labrecque', 'F'],
       [186, 'JulieBeauchemin@teleworm.us', 'Julie Beauchemin', 'F'],
       [187, 'KarelDandonneau@dayrep.com', 'Karel Dandonneau', 'M'],
       [188, 'PaienBeauchesne@rhyta.com', 'Paien Beauchesne', 'M'],
       [189, 'AdeleClavette@cuvox.de', 'Adele Clavette', 'F'],
       [190, 'LotyeJodion@fleckens.hu', 'Lotye Jodion', 'F'],
       [191, 'AmaranteLacroix@fleckens.hu', 'Amarante Lacroix', 'F'],
       [192, 'XarlesCaisse@jourrapide.com', 'Xarles Caisse', 'M'],
       [193, 'LealaLemelin@dayrep.com', 'Leala Lemelin', 'F'],
       [194, 'ChantalLamoureux@jourrapide.com', 'Chantal Lamoureux', 'F'],
       [195, 'NinetteAdler@superrito.com', 'Ninette Adler', 'F'],
       [196, 'EmmanuelleLabrie@einrot.com', 'Emmanuelle Labrie', 'F'],
       [197, 'HuonDeLaRonde@rhyta.com', 'Huon De La Ronde', 'M'],
       [198, 'SimoneSt-Pierre@jourrapide.com', 'Simone St- Pierre', 'F'],
       [199, 'PeverellMazuret@dayrep.com', 'Peverell Mazuret', 'M'],
       [200, 'LorrainePaulet@einrot.com', 'Lorraine Paulet', 'F'],
       [201, 'DemiLazure@cuvox.de', 'Demi Lazure', 'F'],
       [202, 'AgramantGrandpre@rhyta.com', 'Agramant Grandpre', 'M'],
       [203, 'ClothildeBerie@teleworm.us', 'Clothilde Berie', 'F'],
       [204, 'AimeMarseau@dayrep.com', 'Aime Marseau', 'M'],
       [205, 'RogerDeLaRonde@gustr.com', 'Roger De La Ronde', 'M'],
       [206, 'AiglentinaMarcheterre@superrito.com',
        'Aiglentina Marcheterre', 'F'],
       [207, 'NoemiLaisne@rhyta.com', 'Noemi Laisne', 'F'],
       [208, 'DenisPatenaude@einrot.com', 'Denis Patenaude', 'M'],
       [209, 'JulienBeriault@rhyta.com', 'Julien Beriault', 'M'],
       [210, 'MartheQuerry@einrot.com', 'Marthe Querry', 'F'],
       [211, 'ParfaitBedard@armyspy.com', 'Parfait Bedard', 'M'],
       [212, 'MandelBarteaux@gustr.com', 'Mandel Barteaux', 'M'],
       [213, 'PauletteLemaitre@fleckens.hu', 'Paulette Lemaitre', 'F'],
       [214, 'YoletteLanoie@dayrep.com', 'Yolette Lanoie', 'F'],
       [215, 'LucilleBaron@superrito.com', 'Lucille Baron', 'F'],
       [216, 'ChappellSarrazin@rhyta.com', 'Chappell Sarrazin', 'M'],
       [217, 'GanoHetu@fleckens.hu', 'Gano Hetu', 'M'],
       [218, 'MinetteRoy@fleckens.hu', 'Minette Roy', 'F'],
       [219, 'RoslynChalifour@cuvox.de', 'Roslyn Chalifour', 'M'],
       [220, 'KarelBazinet@einrot.com', 'Karel Bazinet', 'M'],
       [221, 'JosetteBordeleau@einrot.com', 'Josette Bordeleau', 'F'],
       [222, 'LangleyCaron@armyspy.com', 'Langley Caron', 'M'],
       [223, 'ClaudeDandonneau@jourrapide.com', 'Claude Dandonneau', 'F'],
       [224, 'ApollineMichaud@superrito.com', 'Apolline Michaud', 'F'],
       [225, 'PascalineBeaudry@rhyta.com', 'Pascaline Beaudry', 'F'],
       [226, 'FleurCaouette@jourrapide.com', 'Fleur Caouette', 'F'],
       [227, 'FrancisMasse@jourrapide.com', 'Francis Masse', 'M']],
      dtype=object)

In [ ]:
clients = df
emails = clients['email']
#vars = ['nom', 'email']
#clients[vars]
extract = clients[['nom', 'email']]
print(type(clients))
print(type(extract))
print(type(emails))
print(emails.dtypes)
print(emails.shape)
print(emails.head)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
object
(228,)
<bound method NDFrame.head of 0            LaurentDagenais@rhyta.com
1                GuyMarois@fleckens.hu
2            BeaufortLesage@einrot.com
3            RussellDurand@armyspy.com
4                 AlexisRiel@rhyta.com
                    ...
223    ClaudeDandonneau@jourrapide.com
224      ApollineMichaud@superrito.com
225         PascalineBeaudry@rhyta.com
226       FleurCaouette@jourrapide.com
227        FrancisMasse@jourrapide.com
Name: email, Length: 228, dtype: object>

In [ ]:
#clients[["email"]]
clients['identifiant'] += 1
clients
clients['new_id'] = range(0, len(clients))
clients
#clients = clients.drop(columns=['new_id', 'email'])
clients = pd.read_csv('~/Downloads/P2C1_clients/clients.csv')
clients
del clients['email']
clients.pop('genre')
clients

     identifiant                nom
0              0   Laurent Dagenais
1              1         Guy Marois
2              2    Beaufort Lesage
3              3     Russell Durand
4              4        Alexis Riel
..           ...                ...
223          223  Claude Dandonneau
224          224   Apolline Michaud
225          225  Pascaline Beaudry
226          226     Fleur Caouette
227          227      Francis Masse

[228 rows x 2 columns]

In [ ]:
clients = pd.read_csv('~/Downloads/P2C1_clients/clients.csv')
clients.rename(columns={'identifiant' : 'id', 'email' : 'mel'}, inplace=True)
#clients['id'].astype(float)
#clients.dtypes
#clients.sort_values('id', ascending = False, inplace = True)
#clients.sort_values(['nom', 'mel'], ascending = [True, False], inplace = True)
#clients
clients

      id                              mel                nom genre
0      0        LaurentDagenais@rhyta.com   Laurent Dagenais     M
1      1            GuyMarois@fleckens.hu         Guy Marois     M
2      2        BeaufortLesage@einrot.com    Beaufort Lesage     M
3      3        RussellDurand@armyspy.com     Russell Durand     M
4      4             AlexisRiel@rhyta.com        Alexis Riel     M
..   ...                              ...                ...   ...
223  223  ClaudeDandonneau@jourrapide.com  Claude Dandonneau     F
224  224    ApollineMichaud@superrito.com   Apolline Michaud     F
225  225       PascalineBeaudry@rhyta.com  Pascaline Beaudry     F
226  226     FleurCaouette@jourrapide.com     Fleur Caouette     F
227  227      FrancisMasse@jourrapide.com      Francis Masse     M

[228 rows x 4 columns]

In [ ]:
test = pd.DataFrame(np.arange(12).reshape(3, 4), columns=['A', 'B', 'C', 'D'])
test

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
data = {'fix' : ['a', 'b', 'b', 'a', 'b'], 'col' : [3, 4, 10, 7, 6]}
test = pd.DataFrame(data)
test

  fix  col
0   a    3
1   b    4
2   b   10
3   a    7
4   b    6

In [ ]:
test.groupby('fix').mean()

          col
fix
a    5.000000
b    6.666667

In [ ]:
import pandas as pd
notes = pd.read_csv(r'C:\Users\franc\Downloads\notes.csv')
notes

                   nom          matiere  note
0     Laurent Dagenais         Français    16
1           Guy Marois         Français    13
2      Beaufort Lesage         Français     8
3       Russell Durand         Français    10
4          Alexis Riel         Français    15
..                 ...              ...   ...
79    Agrican Foucault  Physique/Chimie     9
80  Prunella Josseaume  Physique/Chimie     6
81      Yseult Charest  Physique/Chimie    16
82      Dorothee Aupry  Physique/Chimie    17
83       Amaury Reault  Physique/Chimie     8

[84 rows x 3 columns]

In [ ]:
notes.groupby('matiere').mean()

                      note
matiere
Biologie         10.952381
Français         12.857143
Mathématiques    11.333333
Physique/Chimie  11.523810

In [ ]:
moyennes = notes.groupby('nom').mean()
moyennes.reset_index(inplace=True)
moyennes
#moyennes['note'] < 10
#type(moyennes)
bad = moyennes.loc[moyennes['note'] < 10]
bad.shape[0]

6

In [ ]:
notes_hg = pd.read_csv(r'C:\Users\franc\Downloads\notes_sup.csv')
notes_hg
notes = pd.concat([notes, notes_hg])
notes

                   nom   matiere  note
0     Laurent Dagenais  Français    16
1           Guy Marois  Français    13
2      Beaufort Lesage  Français     8
3       Russell Durand  Français    10
4          Alexis Riel  Français    15
..                 ...       ...   ...
37    Agrican Foucault   Anglais    10
38  Prunella Josseaume   Anglais    20
39      Yseult Charest   Anglais     7
40      Dorothee Aupry   Anglais    11
41       Amaury Reault   Anglais    12

[126 rows x 3 columns]

In [ ]:
notes.groupby('matiere').mean()

                          note
matiere
Anglais              12.428571
Biologie             10.952381
Français             12.857143
Histoire/Géographie  14.047619
Mathématiques        11.333333
Physique/Chimie      11.523810

In [ ]:
notes.pivot_table(index='nom', columns='matiere', values='note')

matiere,Anglais,Biologie,Français,Histoire/Géographie,Mathématiques,Physique/Chimie
nom,,,,,,
Aceline Hughes,18,15,12,12,13,10
Agate Grandbois,17,19,12,9,9,17
Agramant Pepin,10,6,17,20,18,16
Agrican Foucault,10,14,10,14,13,9
Aiglentina Lambert,7,7,16,15,6,5
Alexis Riel,13,5,15,20,5,11
Amaury Reault,12,7,8,18,11,8
Beaufort Lesage,12,8,8,8,15,18
Byron Lefebvre,12,15,13,15,19,8
Dorothee Aupry,11,16,13,20,13,17
Florus Devoe,12,11,10,14,19,15
Gaston Brisette,7,17,19,8,6,12
Guy Marois,11,8,13,13,17,11
Laurent Dagenais,7,17,16,18,7,13
Leon Lapresse,13,8,17,18,7,17
Normand Arsenault,19,6,17,10,10,9
Orville Routhier,7,6,6,20,12,9
Prunella Josseaume,20,14,19,9,11,6
Russell Durand,17,12,10,19,5,7
Theodore Clavet,19,6,8,8,16,8
Yseult Charest,7,13,11,7,6,16

In [ ]:
commandes = pd.read_csv(r'C:\Users\franc\Downloads\csv_P2_quizz\commande.csv')
commandes

     id  nombre
0    70       2
1    41       4
2    72       2
3    92       8
4    73       1
..   ..     ...
995  37       2
996  83       6
997  44       3
998  23       9
999  15       1

[1000 rows x 2 columns]

In [ ]:
produits = pd.read_csv(r'C:\Users\franc\Downloads\csv_P2_quizz\produits.csv')
produits

    id  prix
0    0  24.8
1    1  13.1
2    2  23.7
3    3  16.0
4    4  19.0
..  ..   ...
95  95  21.2
96  96  18.8
97  97   8.9
98  98  20.0
99  99  11.8

[100 rows x 2 columns]

In [ ]:
ventes_vol = commandes.groupby('id').count().sort_values('nombre', ascending=False)
ventes_vol

    nombre
id
66      17
8       17
30      17
65      16
94      16
..     ...
58       4
28       4
95       4
62       4
68       3

[100 rows x 1 columns]

In [ ]:
commandes_ca = pd.merge(commandes, produits, how='left')
commandes_ca['total'] = commandes_ca['nombre'] * commandes_ca['prix']
commandes_ca = commandes_ca.sort_values('total')
commandes_ca

     id  nombre  prix  total
911  94       1   5.8    5.8
84   94       1   5.8    5.8
179  92       1   7.4    7.4
710  55       1   8.0    8.0
251  55       1   8.0    8.0
..   ..     ...   ...    ...
333  77      10  28.0  280.0
736  52       9  32.4  291.6
215  19      10  31.6  316.0
879  19      10  31.6  316.0
304  52      10  32.4  324.0

[1000 rows x 4 columns]